/**
* File was generated by animation packager.
*/
#ifndef		_BG_INGAME_N_COLOR_I6_H
#define		_BG_INGAME_N_COLOR_I6_H


#define		BG_INGAME_N_COLOR_I6_NUM_MODULES				8
#define		BG_INGAME_N_COLOR_I6_MODULE_MAP05				0
#define		BG_INGAME_N_COLOR_I6_MODULE_MAP05				1
#define		BG_INGAME_N_COLOR_I6_MODULE_MAP05				2
#define		BG_INGAME_N_COLOR_I6_MODULE_MAP05				3


#define		BG_INGAME_N_COLOR_I6_NUM_FRAMES				5


#define		BG_INGAME_N_COLOR_I6_NUM_ANIMS				0


#endif