/**
* File was generated by animation packager.
*/
#ifndef		_BG_INGAME_I6_H
#define		_BG_INGAME_I6_H


#define		BG_INGAME_I6_NUM_MODULES				16
#define		BG_INGAME_I6_MODULE_MAP03				2
#define		BG_INGAME_I6_MODULE_MAP01				3
#define		BG_INGAME_I6_MODULE_MAP04				4
#define		BG_INGAME_I6_MODULE_MAP02				5
#define		BG_INGAME_I6_MODULE_MAP05				12
#define		BG_INGAME_I6_MODULE_MAP06				13


#define		BG_INGAME_I6_NUM_FRAMES				5


#define		BG_INGAME_I6_NUM_ANIMS				0


#endif