/**
* File was generated by animation packager.
*/
#ifndef		_FONT_HUD_TEXT_INGAME_I6_H
#define		_FONT_HUD_TEXT_INGAME_I6_H


#define		FONT_HUD_TEXT_INGAME_I6_NUM_MODULES				95


#define		FONT_HUD_TEXT_INGAME_I6_NUM_FRAMES				95


#define		FONT_HUD_TEXT_INGAME_I6_NUM_ANIMS				0


#endif