/**
* File was generated by animation packager.
*/
#ifndef		_FONT_LOGO_H
#define		_FONT_LOGO_H


#define		FONT_LOGO_NUM_MODULES				11


#define		FONT_LOGO_NUM_FRAMES				25


#define		FONT_LOGO_NUM_ANIMS				0


#endif