/**
* File was generated by animation packager.
*/
#ifndef		_HUD_TUT_I4_H
#define		_HUD_TUT_I4_H


#define		HUD_TUT_I4_NUM_MODULES				17


#define		HUD_TUT_I4_NUM_FRAMES				11
#define		HUD_TUT_I4_FRAME_1				0
#define		HUD_TUT_I4_FRAME_2				1
#define		HUD_TUT_I4_FRAME_3				2
#define		HUD_TUT_I4_FRAME_4				3
#define		HUD_TUT_I4_FRAME_5				4
#define		HUD_TUT_I4_FRAME_6				5
#define		HUD_TUT_I4_FRAME_7				6
#define		HUD_TUT_I4_FRAME_8				7
#define		HUD_TUT_I4_FRAME_9				8
#define		HUD_TUT_I4_FRAME_10				9
#define		HUD_TUT_I4_FRAME_CONTINUE				10


#define		HUD_TUT_I4_NUM_ANIMS				0


#endif