/**
* File was generated by animation packager.
*/
#ifndef		_HUD_INGAME_TITLE_I6_H
#define		_HUD_INGAME_TITLE_I6_H


#define		HUD_INGAME_TITLE_I6_NUM_MODULES				1


#define		HUD_INGAME_TITLE_I6_NUM_FRAMES				1


#define		HUD_INGAME_TITLE_I6_NUM_ANIMS				0


#endif