/**
* File was generated by animation packager.
*/
#ifndef		_HUD_TUT_I6_H
#define		_HUD_TUT_I6_H


#define		HUD_TUT_I6_NUM_MODULES				28


#define		HUD_TUT_I6_NUM_FRAMES				11
#define		HUD_TUT_I6_FRAME_1				0
#define		HUD_TUT_I6_FRAME_2				1
#define		HUD_TUT_I6_FRAME_3				2
#define		HUD_TUT_I6_FRAME_4				3
#define		HUD_TUT_I6_FRAME_5				4
#define		HUD_TUT_I6_FRAME_6				5
#define		HUD_TUT_I6_FRAME_7				6
#define		HUD_TUT_I6_FRAME_8				7
#define		HUD_TUT_I6_FRAME_9				8
#define		HUD_TUT_I6_FRAME_10				9
#define		HUD_TUT_I6_FRAME_11				10


#define		HUD_TUT_I6_NUM_ANIMS				0


#endif