/**
* File was generated by animation packager.
*/
#ifndef		_HUD_INGAME_SHARE_I6_H
#define		_HUD_INGAME_SHARE_I6_H


#define		HUD_INGAME_SHARE_I6_NUM_MODULES				5


#define		HUD_INGAME_SHARE_I6_NUM_FRAMES				5


#define		HUD_INGAME_SHARE_I6_NUM_ANIMS				0


#endif