/**
* File was generated by animation packager.
*/
#ifndef		_HUD_RATING_I6_H
#define		_HUD_RATING_I6_H


#define		HUD_RATING_I6_NUM_MODULES				7


#define		HUD_RATING_I6_NUM_FRAMES				10
#define		HUD_RATING_I6_FRAME_BOARD				0
#define		HUD_RATING_I6_FRAME_CONGRA				1
#define		HUD_RATING_I6_FRAME_LATER				2
#define		HUD_RATING_I6_FRAME_YES				6


#define		HUD_RATING_I6_NUM_ANIMS				8
#define		HUD_RATING_I6_ANIM_LATER				0
#define		HUD_RATING_I6_ANIM_YES				4


#endif