/**
* File was generated by animation packager.
*/
#ifndef		_HUD_GAMEOVER_I6_H
#define		_HUD_GAMEOVER_I6_H


#define		HUD_GAMEOVER_I6_NUM_MODULES				2


#define		HUD_GAMEOVER_I6_NUM_FRAMES				2
#define		HUD_GAMEOVER_I6_FRAME_TITLE				0


#define		HUD_GAMEOVER_I6_NUM_ANIMS				0


#endif