/**
* File was generated by animation packager.
*/
#ifndef		_OBJECT_01_I6_H
#define		_OBJECT_01_I6_H


#define		OBJECT_01_I6_NUM_MODULES				1


#define		OBJECT_01_I6_NUM_FRAMES				1


#define		OBJECT_01_I6_NUM_ANIMS				0


#endif