/**
* File was generated by animation packager.
*/
#ifndef		_OBJECT_02_I6_H
#define		_OBJECT_02_I6_H


#define		OBJECT_02_I6_NUM_MODULES				2


#define		OBJECT_02_I6_NUM_FRAMES				1
#define		OBJECT_02_I6_FRAME_FISH				0


#define		OBJECT_02_I6_NUM_ANIMS				0


#endif